version: '3.8'
services:
 server:
   image: frascarfato/ratatouille23:server
   ports:
     - 8080:8080
   environment:
     - SERVER_PORT=8080
     - MYSQL_USER=ratatouille
     - MYSQL_PASSWORD=ratatouille
     - MYSQL_URL=jdbc:mysql://database/ratatouille
   depends_on:
     - database

 database:
    image: mysql:8.0
    ports:
      - 3307:3306 #TODO
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=ratatouille
      - MYSQL_PASSWORD=ratatouille
      - MYSQL_DATABASE=ratatouille