version: '3.8'
services:
 server:
   image: myserver-image
   ports:
     - 8080:8080
   environment:
     - SERVER_PORT=8080
     - MYSQL_USER=ratatouille
     - MYSQL_PASSWORD=ratatouille
     - MYSQL_URL=jdbc:mysql://database/ratatouille
   volumes:
     - ./:/app
   depends_on:
     - database

 database:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=ratatouille
      - MYSQL_PASSWORD=ratatouille
      - MYSQL_DATABASE=ratatouille
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
    mysql_data:
    mysql_config: